### PR TITLE
Fix Android Build (try 2)

### PR DESCRIPTION
**Pull request by vinnyjth**

### CODE REVIEW

**Comment by vinnyjth** [comment]
@conrad-vanl can you give this a shot and make sure it builds for you locally?

**Comment by conrad-vanl** [comment]
<details><summary>😞</summary>
ERROR: Unable to resolve dependency for ':app@debug/compileClasspath': Could not resolve project :react-native-custom-tabs.
Show Details
Affected Modules: app


ERROR: Unable to resolve dependency for ':app@debugAndroidTest/compileClasspath': Could not resolve project :react-native-custom-tabs.
Show Details
Affected Modules: app


ERROR: Unable to resolve dependency for ':app@debugUnitTest/compileClasspath': Could not resolve project :react-native-custom-tabs.
Show Details
Affected Modules: app


ERROR: Unable to resolve dependency for ':app@release/compileClasspath': Could not resolve project :react-native-custom-tabs.
Show Details
Affected Modules: app


ERROR: Unable to resolve dependency for ':app@releaseUnitTest/compileClasspath': Could not resolve project :react-native-custom-tabs.
Show Details
Affected Modules: app


WARNING: Configuration 'compile' is obsolete and has been replaced with 'implementation' and 'api'.
It will be removed at the end of 2018. For more information see: http://d.android.com/r/tools/update-dependency-configurations.html
Affected Modules: android-react-native-device-info, android-react-native-music-control, react-native-onesignal


WARNING: Configuration 'testCompile' is obsolete and has been replaced with 'testImplementation'.
It will be removed at the end of 2018. For more information see: http://d.android.com/r/tools/update-dependency-configurations.html
Affected Modules: react-native-onesignal


WARNING: The specified Android SDK Build Tools version (26.0.1) is ignored, as it is below the minimum supported version (28.0.3) for Android Gradle Plugin 3.3.1.
Android SDK Build Tools 28.0.3 will be used.
To suppress this warning, remove "buildToolsVersion '26.0.1'" from your build.gradle file, as each version of the Android Gradle Plugin now has a default version of the build tools.
Remove Build Tools version and sync project
Affected Modules: android-react-native-music-control
</details>

I tried blowing out node_modules and stuff. Not sure...

**Comment by vinnyjth** [comment]
Man! I'll blow out my `node_modules` and try again. I might have made a change to `react-native-music-control`'s build.gradle that is not in their latest `npm`.....

**Comment by conrad-vanl** [comment]
Most of those errors are still referencing `react-native-custom-tabs` which I thought we got rid of though :/

**Comment by conrad-vanl** [comment]
could just be my android studio still?

**Comment by vinnyjth** [comment]
@conrad-vanl Potentially. I had luck restarting and cleaning before trying to build. I definitely got rid of `react-native-custom-tabs`. 

Also, I had some changes locally to that `music-control`'s build.gradle. Those changes are in their github, but not released, so I made an issue.

https://github.com/tanguyantoine/react-native-music-control/issues/252

**Comment by vinnyjth** [comment]
@conrad-vanl Actually hold on I might have forgotten to push something related to custom tabs....

**Comment by vinnyjth** [comment]
@conrad-vanl When you have a minute, give this a shot.

**Comment by conrad-vanl** [comment]
Android Studio builds now, but getting a runtime packaging error:

image

Was this successful for you?

**Comment by vinnyjth** [comment]
After many false starts, I think this is now good to go.

**Comment by conrad-vanl** [comment]
Good job. Works.

**Pull request merged**
